name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - master

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "${{ github.event.head_commit.author.email }}"
          git config --global user.name "${{ github.event.head_commit.author.name }}"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Tag Release
        id: tag_release
        run: |
          tag_name="v1.0-${GITHUB_SHA::8}"
          git tag -a $tag_name -m "Release $tag_name"
          echo "::set-output name=tag::$tag_name"
        if: success()

      - name: Push Tag
        run: git push origin ${{ steps.tag_release.outputs.tag }}
        if: success()

      - name: Track Deployment with Raygun
        run: |
          bash .github/workflows/raygun_deployment_tracking.sh -t ${{ secrets.RAYGUN_PAT_TOKEN }} \
                                 -a ${{ secrets.RAYGUN_API_KEY }} \
                                 -v ${{ steps.tag_release.outputs.tag }} \
                                 -o "${{ github.event.head_commit.author.name }}" \
                                 -e "${{ github.event.head_commit.author.email }}" \
                                 -n "Deployment notes" \
                                 -i "GitHub" \
                                 -s "git" \
                                 -d "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
