# YAML file for deployment registration with Raygun
name: "Raygun Deployment Registration"
description: "A script to register deployment with Raygun"

jobs:
  register-deployment:
    steps:
      - name: Set deployment variables
        run: |
          RAYGUN_PAT_TOKEN: ${{ secrets.RAYGUN_PAT_TOKEN }}
          RAYGUN_API_KEY: ${{ secrets.RAYGUN_API_KEY }}
          DEPLOYMENT_VERSION: ${{ inputs.version }}
          DEPLOYMENT_OWNER_NAME: ${{ inputs.owner_name }}
          DEPLOYMENT_OWNER_EMAIL: ${{ inputs.email }}
          DEPLOYMENT_NOTES: ${{ inputs.notes }}
          DEPLOYMENT_SCM_IDENTIFIER: ${{ inputs.scm_identifier }}
          DEPLOYMENT_SCM_TYPE: ${{ inputs.scm_type }}
          DEPLOYMENT_TIME: ${{ inputs.deployed_at }}

      - name: Validate mandatory parameters
        run: |
          if [ -z "${RAYGUN_PAT_TOKEN}" ] || [ -z "${RAYGUN_API_KEY}" ] || [ -z "${DEPLOYMENT_VERSION}" ]; then
            echo "Error: Mandatory parameters missing. Exiting..."
            exit 1
          fi

      - name: Register Deployment
        run: |
          url="https://api.raygun.com/v3/applications/api-key/${RAYGUN_API_KEY}/deployments"

          json_properties=("\"version\": \"${DEPLOYMENT_VERSION}\"")

          if [ -n "${DEPLOYMENT_OWNER_NAME}" ]; then
            json_properties+=("\"ownerName\": \"${DEPLOYMENT_OWNER_NAME}\"")
          fi

          if [ -n "${DEPLOYMENT_OWNER_EMAIL}" ]; then
            json_properties+=("\"emailAddress\": \"${DEPLOYMENT_OWNER_EMAIL}\"")
          fi

          if [ -n "${DEPLOYMENT_NOTES}" ]; then
            json_properties+=("\"comment\": \"${DEPLOYMENT_NOTES}\"")
          fi

          if [ -n "${DEPLOYMENT_SCM_IDENTIFIER}" ]; then
            json_properties+=("\"scmIdentifier\": \"${DEPLOYMENT_SCM_IDENTIFIER}\"")
          fi

          if [ -n "${DEPLOYMENT_SCM_TYPE}" ]; then
            json_properties+=("\"scmType\": \"${DEPLOYMENT_SCM_TYPE}\"")
          fi

          if [ -n "${DEPLOYMENT_TIME}" ]; then
            json_properties+=("\"deployedAt\": \"${DEPLOYMENT_TIME}\"")
          fi

          arrayString=$(IFS=',' ; echo "${json_properties[*]}")

          json_string="{$arrayString}"

          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${RAYGUN_PAT_TOKEN}" \
            -d "${json_string}" \
            "${url}")

          status_code=$(printf "%s" "$response" | tail -c 3)

          if [ "${status_code}" -eq "201" ]; then
            echo "Deployment registered with Raygun"
          else
            echo "Failed to register deployment with Raygun"
          fi
